cse-config-order: 100

## Spring Boot configurations
spring:
  application:
    name: product-service
server:
  port: 8089
# alpha
alpha:
  cluster:
    address: 127.0.0.1:7080

## CSE configurations

APPLICATION_ID: houseapp
service_description:
  name: ${spring.application.name}
  version: 0.0.1
  environment: development
cse:
  service:
    registry:
      address: http://localhost:30100
      instance:
        watch: false

  rest:
    address: 0.0.0.0:8089
    server:
      thread-count: 10
  credentials:
    accessKey: BUDCVWSAW04UZVLSZBQR
    secretKey: BHixEctCJFbTkPUVUUjRDSeVwMAknlAy5oB7idgR
    akskCustomCipher: default

  handler:
    chain:
      Provider:
        default: qps-flowcontrol-provider,bizkeeper-provider,saga-provider
      Consumer:
        default: qps-flowcontrol-consumer,loadbalance,bizkeeper-consumer,saga-consumer